// <auto-generated />
using System;
using EmployeeManagement.Data.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmpManagementMVC.Migrations
{
    [DbContext(typeof(EmployeeAppDataCore))]
    [Migration("20190708142512_InitialCreate_Five")]
    partial class InitialCreate_Five
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeManagement.Data.Core.Department", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<string>("DepartmentName");

                    b.Property<Guid?>("DepartmentTypeId");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime>("UpdatedDateTime");

                    b.HasKey("DepartmentId");

                    b.HasIndex("DepartmentTypeId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EmployeeManagement.Data.Core.DepartmentType", b =>
                {
                    b.Property<Guid>("DepartmentTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<string>("DepartmentName");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime>("UpdatedDateTime");

                    b.HasKey("DepartmentTypeId");

                    b.ToTable("DepartmentType");
                });

            modelBuilder.Entity("EmployeeManagement.Data.Core.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Department");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeManagement.Data.Core.Department", b =>
                {
                    b.HasOne("EmployeeManagement.Data.Core.DepartmentType", "DepartmentType")
                        .WithMany()
                        .HasForeignKey("DepartmentTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
